# Generated by Django 6.0 on 2026-01-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueId', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=50)),
                ('guestCount', models.IntegerField()),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('basePrice', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=500)),
            ],
        ),
    ]
