# Generated by Django 6.0 on 2026-01-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.planner'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='plannerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='totalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='planner',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='venueId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planner',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
