# Generated by Django 6.0 on 2026-01-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookingrequest_planner_bookingrequest_plannername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='paymentStatus',
            field=models.CharField(blank=True, default='unpaid', max_length=20, null=True),
        ),
    ]
